### ISSUE TITLE
chrome driver problem

### ISSUE THREAD

**Issue by vahidqo** [hejazizo/us-visa-rescheduler#11]
Hi,

I receive this error:

```
Traceback (most recent call last):
  File "C:\test\us-visa-rescheduler-main\src\main.py", line 36, in <module>
    driver = get_driver(local_use=LOCAL_USE, hub_address=HUB_ADDRESS)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\test\us-visa-rescheduler-main\src\utils.py", line 40, in get_driver
    dr = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\test\us-visa-rescheduler-main\us\Lib\site-packages\webdriver_manager\chrome.py", line 37, in install
    driver_path = self._get_driver_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\test\us-visa-rescheduler-main\us\Lib\site-packages\webdriver_manager\core\manager.py", line 29, in _get_driver_path
    binary_path = self.driver_cache.find_driver(driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\test\us-visa-rescheduler-main\us\Lib\site-packages\webdriver_manager\core\driver_cache.py", line 95, in find_driver
    driver_version = driver.get_version()
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\test\us-visa-rescheduler-main\us\Lib\site-packages\webdriver_manager\core\driver.py", line 42, in get_version
    self.get_latest_release_version()
  File "C:\test\us-visa-rescheduler-main\us\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 44, in get_latest_release_version
    resp = self._http_client.get(url=latest_release_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\test\us-visa-rescheduler-main\us\Lib\site-packages\webdriver_manager\core\http.py", line 33, in get
    self.validate_response(resp)
  File "C:\test\us-visa-rescheduler-main\us\Lib\site-packages\webdriver_manager\core\http.py", line 15, in validate_response
    raise ValueError(f"There is no such driver by url {resp.url}")
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_119.0.6045
```

**Comment by masoudrahimi39** [comment]
It appears that the error is related to the attempt to download the ChromeDriver for a specific version of Google Chrome (version 119.0.6045), and it seems that there is no ChromeDriver available for that version.

Just **Update ChromeDriver Manager** by running below:
`pip install --upgrade webdriver_manager`
